import type { AdminUser, Competition, Coach, Enquiry, GalleryAlbum, Match, Player, Post, TrialApplication } from './types'
import { photo } from './types'

const names = ['Ethan Cole','Noah Williams','Leo Grant','Mason Reed','Kai Bennett','Theo Brooks','Oscar Hayes','Luca Shaw','Aiden Fox','Jude Miles','Finn Carter','Rory Lane','Max Dean','Sam Ellis']
const positions = [['FWD','Centre Forward'],['MID','Central Midfielder'],['DEF','Centre Back'],['GK','Goalkeeper']] as const
export const players: Player[] = names.map((fullName,i)=>{const [firstName,lastName]=fullName.split(' '); const [position,positionText]=positions[i%4]; return {id:`p${i+1}`,slug:fullName.toLowerCase().replace(' ','-'),firstName,lastName,dateOfBirth:`${2007+i%5}-0${(i%8)+1}-1${i%9}`,position,positionText,jerseyNumber:[9,8,4,1,11,6,5,10,2,7,3,12,14,15][i],preferredFoot:i%3===0?'Left':'Right',heightCm:168+i%9,weightKg:60+i%8,nationality:i%4===0?'England':i%4===1?'Nigeria':'Spain',photoUrl:photo(i+1),bio:`${fullName} is a committed Blaze FC academy player with an instinct for the game and a relentless appetite to improve.`,highlightVideoUrl:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',ageGroup:`U${13+(i%3)*2}`,status:i===12?'trial':i===13?'alumni':'active',isPublic:true} as Player})
export const competitions: Competition[] = [
{id:'c1',slug:'youth-premier-league',name:'Youth Premier League',season:'2025/26',type:'league',status:'ongoing',startDate:'2025-09-01',endDate:'2026-05-15'},
{id:'c2',slug:'academy-cup',name:'Academy Cup',season:'2025/26',type:'cup',status:'ongoing',startDate:'2025-10-01',endDate:'2026-04-20'},
{id:'c3',slug:'london-youth-trophy',name:'London Youth Trophy',season:'2025',type:'tournament',status:'completed',startDate:'2025-06-01',endDate:'2025-07-12'},
{id:'c4',slug:'winter-series',name:'Winter Series',season:'2026',type:'tournament',status:'upcoming',startDate:'2026-11-01',endDate:'2026-12-12'}]
export const matches: Match[] = Array.from({length:12},(_,i)=>({id:`m${i+1}`,slug:`blaze-fc-${i+1}`,competitionId:i%2?'c2':'c1',date:`2026-${String((i%8)+1).padStart(2,'0')}-${String((i%24)+1).padStart(2,'0')}`,opponent:['Eastside United','Riverside FC','North London Athletic','Kingsway Academy'][i%4],homeOrAway:i%2?'Away':'Home',scoreFor:i<8?2+(i%3):null,scoreAgainst:i<8?i%3:null,youtubeUrl:'https://youtu.be/dQw4w9WgXcQ',report:'A composed performance from the squad, with excellent movement off the ball and a deserved result.',venue:i%2?'Riverside Sports Ground':'Blaze Training Centre'}))
export const posts: Post[] = Array.from({length:6},(_,i)=>({id:`post${i+1}`,slug:`academy-news-${i+1}`,title:['Blaze FC secure first place in weekend thriller','Inside the academy: building complete players','Five things we learned from the cup run','Meet the next wave of Blaze talent','Coach perspective: standards create confidence','Community day brings the club together'][i],body:'The academy is continuing to grow with purpose. Here is the latest from around Blaze FC, on and off the pitch.',coverImageUrl:photo(20+i),type:i%2?'news':'report',publishedAt:`2026-0${(i%8)+1}-1${i+1}`,relatedMatchId:i<3?`m${i+1}`:undefined}))
export const enquiries: Enquiry[] = Array.from({length:8},(_,i)=>({id:`e${i+1}`,name:['Jamie Morgan','Alex Reed','Priya Shah','Daniel King'][i%4],email:`contact${i+1}@example.com`,phone:'+44 20 7946 0958',message:'I would like to learn more about academy pathways and upcoming trials.',playerId:i%3===0?'p1':undefined,status:i<3?'new':'handled',createdAt:`2026-09-${String(10-i).padStart(2,'0')}`}))
export const trials: TrialApplication[] = Array.from({length:5},(_,i)=>({id:`t${i+1}`,applicantName:['Harvey Young','Mia Green','Isaac Bell','Amara Cole','George Wood'][i],dateOfBirth:'2012-05-14',position:['FWD','MID','DEF','GK','FWD'][i] as Player['position'],guardianName:'Parent / Guardian',contactEmail:`family${i+1}@example.com`,contactPhone:'+44 7700 900123',message:'Excited to attend a trial session.',status:['new','reviewing','invited','declined','new'][i] as TrialApplication['status'],createdAt:`2026-09-${12-i}`}))
export const albums: GalleryAlbum[] = [{id:'a1',slug:'matchday-moments',title:'Matchday moments',date:'September 2026',coverImageUrl:photo(31),imageCount:24},{id:'a2',slug:'academy-life',title:'Academy life',date:'August 2026',coverImageUrl:photo(32),imageCount:18},{id:'a3',slug:'summer-tournament',title:'Summer tournament',date:'July 2026',coverImageUrl:photo(33),imageCount:32}]
export const adminUsers: AdminUser[] = [{id:'u1',name:'Alex Morgan',email:'alex@blazefc.com',role:'admin'},{id:'u2',name:'Jordan Ellis',email:'jordan@blazefc.com',role:'coach'},{id:'u3',name:'Sofia Patel',email:'sofia@blazefc.com',role:'editor'},{id:'u4',name:'Marcus Shaw',email:'marcus@blazefc.com',role:'coach'}]
export const coaches: Coach[] = [{id:'c1',name:'Jordan Ellis',role:'Head Coach',team:'U18 Academy',bio:'Leads the senior academy programme and matchday standards.',photoUrl:photo(41),isActive:true},{id:'c2',name:'Marcus Shaw',role:'Technical Director',team:'All squads',bio:'Owns the technical framework, player development and coach education.',photoUrl:photo(42),isActive:true},{id:'c3',name:'Sofia Patel',role:'Goalkeeping Coach',team:'U13 Academy',bio:'Develops goalkeeper fundamentals, confidence and distribution.',photoUrl:photo(43),isActive:true}]
export const chartData = [{month:'Apr',enquiries:12},{month:'May',enquiries:18},{month:'Jun',enquiries:14},{month:'Jul',enquiries:26},{month:'Aug',enquiries:22},{month:'Sep',enquiries:34}]
